### ISSUE TITLE
error：RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by yyyyiiiinnnn** [eric-yyjau/pytorch-superpoint#105]
I have a problem when running step 1:
epoch:  0
get dataloader
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "train4.py", line 141, in <module>
    args.func(config, output_dir, args)
  File "train4.py", line 41, in train_base
    return train_joint(config, output_dir, args)
  File "train4.py", line 93, in train_joint
    train_agent.train()
  File "/home/yibo/pytorch-sp/Train_model_frontend.py", line 277, in train
    loss_out = self.train_val_sample(sample_train, self.n_iter, True)
  File "/home/yibo/pytorch-sp/Train_model_heatmap.py", line 229, in train_val_sample
    outs = self.net(img.to(self.device))
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yibo/pytorch-sp/models/SuperPointNet_gauss2.py", line 53, in forward
    x1 = self.inc(x)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yibo/pytorch-sp/models/unet_parts.py", line 34, in forward
    x = self.conv(x)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yibo/pytorch-sp/models/unet_parts.py", line 24, in forward
    x = self.conv(x)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/root/miniconda3/envs/superpoint/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR

The problem seems to be in the train_val_sample function in the Train_model_frontend.py file? When I try to print() at the beginning of train_val_sample, the terminal doesn't show my print information.Any help from you is greatly appreciated for me！

**Comment by lzyhero** [comment]
Cuda and Torch versions do not match. I suggest adjusting your cuda and hope this can help you.

**Comment by yyyyiiiinnnn** [comment]
thanks！
