### ISSUE TITLE
An error occurred while running the first step

### ISSUE THREAD

**Issue by hanyunlong233** [eric-yyjau/pytorch-superpoint#17]
Traceback (most recent call last):
  File "train4.py", line 141, in <module>
    args.func(config, output_dir, args)
  File "train4.py", line 41, in train_base
    return train_joint(config, output_dir, args)
  File "train4.py", line 93, in train_joint
    train_agent.train()
  File "/home/hyl/program/pytorch-superpoint/Train_model_frontend.py", line 275, in train
    for i, sample_train in tqdm(enumerate(self.train_loader)):
  File "/home/hyl/anaconda3/envs/py36-sp/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/hyl/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/hyl/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/hyl/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hyl/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hyl/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hyl/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hyl/program/pytorch-superpoint/datasets/SyntheticDataset_gaussian.py", line 443, in __getitem__
    img.squeeze(), inv_homography, mode="bilinear"
  File "/home/hyl/program/pytorch-superpoint/utils/utils.py", line 370, in inv_warp_image
    warped_img = inv_warp_image_batch(img, mat_homo_inv, device, mode)
  File "/home/hyl/program/pytorch-superpoint/utils/utils.py", line 351, in inv_warp_image_batch
    warped_img = F.grid_sample(img, src_pixel_coords, mode=mode, align_corners=True)
TypeError: grid_sample() got an unexpected keyword argument 'align_corners'

I have some questions I'd like to ask. I hope you can answer them for me.The above error occurred when I was running the first step, train_joint() will also be used in the next few parts.In addition, how to install roi_pool in the Training tutorial?Hope to get your reply!

**Comment by eric-yyjau** [comment]
Hi @hanyunlong233,

Sorry for the late reply. I think it is the version issue.
Can you upgrade your pytorch to support `grid_sample(align_corners=True)`?
Otherwise, you can delete the keyword `align_corners`:
```
warped_img = F.grid_sample(img, src_pixel_coords, mode=mode)
```
Thanks.

**Comment by hanyunlong233** [comment]
Thank you for your reply.I will try it your way.
