### ISSUE TITLE
Error in the first step.

### ISSUE THREAD

**Issue by Artcs1** [eric-yyjau/pytorch-superpoint#30]
Hi @eric-yyjau. Thanks for the great repo.

I actually have a problem, when I run the first step. It seems to be the data loader but I don't know. Can you give me some hint? 

Error:

_____________________________
Traceback (most recent call last):
  File "train4.py", line 141, in <module>
    args.func(config, output_dir, args)
  File "train4.py", line 41, in train_base
    return train_joint(config, output_dir, args)
  File "train4.py", line 93, in train_joint
    train_agent.train()
  File "/home/jeffri/Desktop/pytorch-superpoint/Train_model_frontend.py", line 275, in train
    for i, sample_train in tqdm(enumerate(self.train_loader)):
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/tqdm/std.py", line 1171, in __iter__
    for obj in iterable:
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/numpy/lib/format.py", line 583, in _read_array_header
    d = safe_eval(header)
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/numpy/lib/utils.py", line 1007, in safe_eval
    return ast.literal_eval(source)
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    {'descr': '<f8', 'fortran_order': False, 'shape': (5, 2), }
                                                                    ^
SyntaxError: invalid character in identifier

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jeffri/Desktop/pytorch-superpoint/datasets/SyntheticDataset_gaussian.py", line 373, in __getitem__
    pnts = np.load(sample["points"])  # (y, x)
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/numpy/lib/format.py", line 717, in read_array
    shape, fortran_order, dtype = _read_array_header(fp, version)
  File "/home/jeffri/anaconda3/envs/py36-sp/lib/python3.6/site-packages/numpy/lib/format.py", line 586, in _read_array_header
    raise ValueError(msg.format(header, e))
ValueError: Cannot parse header: "{'descr': '<f8', 'fortran_order': False, 'shape': (5, 2), }     \xa0                                                    \n"
Exception: SyntaxError('invalid character in identifier', ('<unknown>', 1, 65, "{'descr': '<f8', 'fortran_order': False, 'shape': (5, 2), }     \xa0                                                    \n"))

__________________________________________

Thanks

**Comment by eric-yyjau** [comment]
Hi @Artcs1 

Hope you have solved the issue.
Let me know if you found some bugs to be fixed. Thank you!

**Comment by P66094125** [comment]
I have the same issue, but I have no idea to fix it.
