### ISSUE TITLE
ValueError: need at least one array to stack

### ISSUE THREAD

**Issue by guanchu5** [eric-yyjau/pytorch-superpoint#37]
2931it [11:44,  4.18it/s][01/13/2021 21:05:38 INFO] name: COCO_train2014_000000456425
outputs:  torch.Size([1, 240, 320])
pts:  (3, 0)
heatmap:  (244, 324)
2931it [11:46,  4.15it/s]
Traceback (most recent call last):
  File "export.py", line 408, in <module>
    args.func(config, output_dir, args)
  File "/home/mems/anaconda3/envs/pytorch-superpoint/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "export.py", line 318, in export_detector_homoAdapt_gpu
    pts = fe.soft_argmax_points([pts])
  File "/home/mems/new_home/superpoint/pytorch-superpoint-Test/models/model_wrap.py", line 215, in soft_argmax_points
    patches = np.stack(patches)
  File "<__array_function__ internals>", line 6, in stack
  File "/home/mems/anaconda3/envs/pytorch-superpoint/lib/python3.6/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by eric-yyjau** [comment]
Hi @guanchu5 ,

Looks like the list of patches is empty, which means no points found in the image.
Did you have the pre-trained model loaded correctly?

Maybe you can visualize that?

**Comment by 1962975362** [comment]
@ guanchu5    did you solve this problem

**Comment by 1962975362** [comment]
@guanchu5  hi,  i meet the same problem   did you solve it

**Comment by 20181313zhang** [comment]
Do you change first step? when I change configs/magicpoint_shapes_pair.yaml:line of 74 to 1,It runs very fast(one hours end), but when i run second step, the error is the same as yours.
