### ISSUE TITLE
cuDNN error: CUDNN_STATUS_MAPPING_ERROR

### ISSUE THREAD

**Issue by Zhaoyue628** [eric-yyjau/pytorch-superpoint#47]
Hi! Thank you for your great work! 
I'm sorry to have disturbed you.I ran into a problem while running Step 4 that has been bothering me for a long time. I hope you give me some suggestion.
I'm running on NVIDIA RTX 3090. My experimental environment is as follows.
Requirements:
- python == 3.6.2
- pytorch == 1.4.0 
- torchvision == 0.5.0
- cuda 10.0+cudnn 7.6.3
The problem is shown in the figure below。
Thank you in advance！

**Comment by Zhaoyue628** [comment]
(py36-sp) cczu402@cczu402-MS-7C79:~/ZY/code/pytorch-superpoint-master$ python export.py export_descriptor  configs/magicpoint_repeatability_heatmap.yaml superpoint_hpatches_test
export.py:401: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(f)
check config!!  {'data': {'name': 'patches_dataset', 'dataset': 'hpatches', 'alteration': 'all', 'preprocessing': {'resize': [240, 320]}}, 'front_end_model': 'Val_model_heatmap', 'model': {'name': 'SuperPointNet_gauss2', 'params': {}, 'detection_threshold': 0.015, 'batch_size': 1, 'eval_batch_size': 1, 'learning_rate': 0.001, 'nms': 4, 'top_k': 1000, 'nn_thresh': 1.0, 'homography_adaptation': {'num': 0}, 'subpixel': {'enable': True, 'patch_size': 5}, 'rand_noise': {'enable': False, 'sigma': 0.2}, 'pretrained': 'logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar'}, 'eval_iter': 1000}
[04/16/2021 13:52:53 INFO] Running command EXPORT_DESCRIPTOR
[04/16/2021 13:52:53 INFO] train on device: cuda:0
[04/16/2021 13:52:53 INFO] => will save everything to logs/superpoint_hpatches_test/checkpoints
[04/16/2021 13:52:53 INFO] workers_test: 1
.......

[04/16/2021 13:52:55 INFO] == test split size 580 in 580 batches
[04/16/2021 13:52:55 INFO] => creating model: SuperPointNet_gauss2
[04/16/2021 13:59:45 INFO] successfully load pretrained model from: logs/superpoint_coco_heat2_0/checkpoints/superPointNet_170000_checkpoint.pth.tar
0it [00:59, ?it/s]
Traceback (most recent call last):
  File "export.py", line 409, in <module>
    args.func(config, output_dir, args)
  File "export.py", line 152, in export_descriptor
    outs = get_pts_desc_from_agent(val_agent, img_0, device=device)
  File "export.py", line 134, in get_pts_desc_from_agent
    img.to(device)
  File "/home/cczu402/ZY/code/pytorch-superpoint-master/Val_model_heatmap.py", line 100, in run
    outs = self.net(images)
  File "/home/cczu402/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cczu402/ZY/code/pytorch-superpoint-master/models/SuperPointNet_gauss2.py", line 53, in forward
    x1 = self.inc(x)
  File "/home/cczu402/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cczu402/ZY/code/pytorch-superpoint-master/models/unet_parts.py", line 34, in forward
    x = self.conv(x)
  File "/home/cczu402/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cczu402/ZY/code/pytorch-superpoint-master/models/unet_parts.py", line 24, in forward
    x = self.conv(x)
  File "/home/cczu402/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cczu402/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/cczu402/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cczu402/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/cczu402/anaconda3/envs/py36-sp/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
