### ISSUE TITLE
Error in running on GPUs

### ISSUE THREAD

**Issue by sanjayr1980** [eric-yyjau/pytorch-superpoint#48]
When we run the below command
python train4.py train_joint configs/superpoint_coco_train_heatmap.yaml superpoint_coco --eval --debug

we get below errors:

File "train4.py", line 145, in <module> args.func(config, output_dir, args) File "train4.py", line 95, in train_joint train_agent.train() File "/mnt/disks/user/project/Train_model_frontend.py", line 277, in train loss_out = self.train_val_sample(sample_train, self.n_iter, True) File "/mnt/disks/user/project/Train_model_heatmap.py", line 315, in train_val_sample **self.desc_params File "/mnt/disks/user/project/utils/loss_functions/sparse_loss.py", line 243, in batch_desc
Traceback (most recent call last): File "train4.py", line 145, in <module> args.func(config, output_dir, args) File "train4.py", line 95, in train_joint train_agent.train() File "/mnt/disks/user/project/Train_model_frontend.py", line 277, in train loss_out = self.train_val_sample(sample_train, self.n_iter, True) File "/mnt/disks/user/project/Train_model_heatmap.py", line 315, in train_val_sample **self.desc_params File "/mnt/disks/user/project/utils/utils.py", line 815,

**Comment by eric-yyjau** [comment]
Hi @sanjayr1980 ,

Is it all the error you got?
I didn't really see what happened here.
Maybe you can paste more complete logs?
