### ISSUE TITLE
Error in the first step

### ISSUE THREAD

**Issue by P66094125** [eric-yyjau/pytorch-superpoint#53]
2021-08-12 20:11:57 DESKTOP-LHM6IOU root[7360] INFO Running command TRAIN_BASE
2021-08-12 20:11:57 DESKTOP-LHM6IOU root[7360] INFO train on device: cuda
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\py36-sp\lib\site-packages\tensorboardX\record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: 'runs/train_base/magicpoint_synth_2021-08-12_20'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train4.py", line 142, in <module>
    args.func(config, output_dir, args)
  File "train4.py", line 41, in train_base
    return train_joint(config, output_dir, args)
  File "train4.py", line 62, in train_joint
    exper_name=args.exper_name, date=True))
  File "C:\Users\User\anaconda3\envs\py36-sp\lib\site-packages\tensorboardX\writer.py", line 299, in __init__
    self._get_file_writer()
  File "C:\Users\User\anaconda3\envs\py36-sp\lib\site-packages\tensorboardX\writer.py", line 354, in _get_file_writer
    **self.kwargs)
  File "C:\Users\User\anaconda3\envs\py36-sp\lib\site-packages\tensorboardX\writer.py", line 106, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "C:\Users\User\anaconda3\envs\py36-sp\lib\site-packages\tensorboardX\event_file_writer.py", line 104, in __init__
    directory_check(self._logdir)
  File "C:\Users\User\anaconda3\envs\py36-sp\lib\site-packages\tensorboardX\record_writer.py", line 51, in directory_check
    os.makedirs(path)
  File "C:\Users\User\anaconda3\envs\py36-sp\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: 'runs/train_base/magicpoint_synth_2021-08-12_20:11:57'

**Comment by uzibuxing** [comment]
excuse me,I find same question, Could you help me how to save this problem

**Comment by P66094125** [comment]
I run it in conda virtual environment in ubuntu to solve this problem.

**Comment by uzibuxing** [comment]
Thank you,sir

**Comment by Y-joker** [comment]
Windows folder cannot contain ':'
