### ISSUE TITLE
error when i use the download lable magicpoint_synth20_homoAdapt100_coco_f1

### ISSUE THREAD

**Issue by FeiXie8** [eric-yyjau/pytorch-superpoint#88]
load labels from:  output/magicpoint_synth20_homoAdapt100_coco_f1/predictions/val
Traceback (most recent call last):
  File "train4.py", line 144, in <module>
    args.func(config, output_dir, args)
  File "train4.py", line 71, in train_joint
    data = dataLoader(config, dataset=task, warp_input=True)
  File "E:\xiefei\pytorch-superpoint-master\utils\loader.py", line 86, in dataLoader
    worker_init_fn=worker_init_fn
  File "E:\tensorflow\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "E:\tensorflow\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py", line 103, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by tutorgaming** [comment]
it seems like the data loader in torch is raising the exception when the Dataloader is trying to use RandomSampler without init the num_samples argument

Relate to this issue on PyTorch repo: https://github.com/pytorch/pytorch/pull/74804

**Comment by tutorgaming** [comment]
Make sure that the Path you put in the field "labels" in the yaml config is correctly defined.
for me is 
```
data:
    # name: 'coco'
    dataset: 'Coco' # 'coco'

    labels: logs/magicpoint_synth_homoAdapt_coco/predictions
```

and now it works.

**Comment by Livesoso** [comment]
think you very much

**Comment by Zzzzcv** [comment]
> load labels from: output/magicpoint_synth20_homoAdapt100_coco_f1/predictions/val Traceback (most recent call last): File "train4.py", line 144, in args.func(config, output_dir, args) File "train4.py", line 71, in train_joint data = dataLoader(config, dataset=task, warp_input=True) File "E:\xiefei\pytorch-superpoint-master\utils\loader.py", line 86, in dataLoader worker_init_fn=worker_init_fn File "E:\tensorflow\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 268, in **init** sampler = RandomSampler(dataset, generator=generator) File "E:\tensorflow\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py", line 103, in **init** "value, but got num_samples={}".format(self.num_samples)) ValueError: num_samples should be a positive integer value, but got num_samples=0

Hello, could you please tell me where you downloaded the pseudo ground truth labels? I can't open the link provided on the README: https://drive.google.com/drive/folders/1nnn0UbNMFF45nov90PJNnubDyinm2f26?usp=sharing

**Comment by ZhangLe407** [comment]
> > 从以下位置加载标签： output/magicpoint_synth20_homoAdapt100_coco_f1/predictions/val 回溯（最近调用最后一次）： 文件 “train4.py”， 第 144 行， 在 args.func（config， output_dir， args） 文件 “train4.py”， 第 71 行， 在 train_joint data = dataLoader（config， dataset=task， warp_input=True） 文件 “E：\xiefei\pytorch-superpoint-master\utils\loader.py”， 第 86 行， 在 dataLoader 中 worker_init_fn=worker_init_fn 文件 “E：\tensorflow\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py“，第 268 行，**init** sampler = RandomSampler（dataset， generator=generator） 文件”E：\tensorflow\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py“，第 103 行，**init** ”value， but got num_samples={}“.format（self.num_samples）） ValueError： num_samples should a positive integer value， but got num_samples=0
> 
> 您好，您能告诉我您从哪里下载了伪真值标签吗？我无法打开 README 上提供的链接：https://drive.google.com/drive/folders/1nnn0UbNMFF45nov90PJNnubDyinm2f26?usp=sharing

I am also unable to download labels using this link. Have you resolved this issue?

**Comment by jk-ux** [comment]
> > > 从以下位置加载标签： output/magicpoint_synth20_homoAdapt100_coco_f1/predictions/val 回溯（最近调用最后一次）： 文件 “train4.py”， 第 144 行， 在 args.func（config， output_dir， args） 文件 “train4.py”， 第 71 行， 在 train_joint data = dataLoader（config， dataset=task， warp_input=True） 文件 “E：\xiefei\pytorch-superpoint-master\utils\loader.py”， 第 86 行， 在 dataLoader 中 worker_init_fn=worker_init_fn 文件 “E：\tensorflow\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py“，第 268 行，**init** sampler = RandomSampler（dataset， generator=generator） 文件”E：\tensorflow\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\sampler.py“，第 103 行，**init** ”value， but got num_samples={}“.format（self.num_samples）） ValueError： num_samples should a positive integer value， but got num_samples=0
> > 
> > 
> > 您好，您能告诉我您从哪里下载了伪真值标签吗？我无法打开 README 上提供的链接：https://drive.google.com/drive/folders/1nnn0UbNMFF45nov90PJNnubDyinm2f26?usp=sharing
> 
> I am also unable to download labels using this link. Have you resolved this issue?

貌似只能自己导出了
